server:
  port: 83
spring:
  application:
    name: nacos-consumer-client83
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-client-service: http://alibaba-nacos-client9001
