server:
  port: 9002

spring:
  application:
    name: alibaba-nacos-client9002
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
