server:
  port: 8008

spring:
  application:
    name: dzcloud-hystrix-service

eureka:
  client:
    #true表示向注册中心展现自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://cloud7001.com:7001/eureka/
  instance:
    instance-id: pay8008
    #访问路径可以显示ip地址
    prefer-ip-address: true