server:
  port: 8009

spring:
  application:
    name: cloud-hystrix-consumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://cloud7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true