server:
  port: 8910

spring:
  application:
    name: cloud-consumer-order-openfeign

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://cloud7001.com:7001/eureka/,http://cloud7002.com:7002/eureka/