server:
  port: 8011

spring:
  application:
    name: getway-service-name
  cloud:
    gateway:
      routes:
        - id: pay_routh          #路由的id,没有固定规则但要求唯一，建议配合服务名
          uri: http://127.0.0.1:8008   #匹配后提供服务路由地址
          predicates:
            - Path=/hystrix/**       #断言，路径相匹配的进行路由


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cloud7001.com:7001/eureka/
    instance:
      instance-id: pay8011
      #访问路径可以显示ip地址
      prefer-ip-address: true